### PR TITLE
Homescreen

### PR DESCRIPTION
**Pull request by Zarkopafilis**
* Node List (with debounced filtering)
* Backend Server Health
* Bus Health
* Plug & Play Table

I need some insights @pavel-kirienko , regarding the refresh rates of each component, of the ones mentioned above.

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
I tried running this locally but couldn't because the local module `@/Router` seems to be missing:

```
 ERROR  Failed to compile with 2 errors                                                                                                 9:53:55 PM

This dependency was not found:

* @/Router in ./src/main.js, ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue

To install it, you can run: npm install --save @/Router
```

**Comment by pavel-kirienko** [comment]
(Weird, I just posted a comment here and it just disappeared. Come on, Microsoft!)

I tried running it locally but couldn't because a local module `@/Router` is missing:

```
 ERROR  Failed to compile with 2 errors                                                                                                 9:53:55 PM

This dependency was not found:

* @/Router in ./src/main.js, ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue

To install it, you can run: npm install --save @/Router
^C
✘-INT ~/uavcan/Yukon/frontend [:4d5c7aa|✚ 2] 
21:54 $ npm install --save @/Router
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@/Router" as it does not contain a package.json file.
```

**Comment by pavel-kirienko** [comment]
(this is my third attempt to leave a comment here; GitHub seems to be seriously malfunctioning)

```
 ERROR  Failed to compile with 2 errors                                                                                                 9:53:55 PM

This dependency was not found:

* @/Router in ./src/main.js, ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue

To install it, you can run: npm install --save @/Router
^C
✘-INT ~/uavcan/Yukon/frontend [:4d5c7aa|✚ 2] 
21:54 $ npm install --save @/Router
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@/Router" as it does not contain a package.json file.
```

**Comment by Zarkopafilis** [comment]
I don't know what's wrong with GitHub, but the router thing does not happen on my side. Try running with npm run dev

**Comment by pavel-kirienko** [comment]
Nope, not working:

```
23:01 $ npm run dev

> frontend@1.0.0 dev /home/pavel/uavcan/Yukon/frontend
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 13% building modules 32/43 modules 11 active ...vel/uavcan/Yukon/frontend/src/App.vue{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
 94% asset optimization

 ERROR  Failed to compile with 2 errors

This dependency was not found:

* @/Router in ./src/main.js, ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue

To install it, you can run: npm install --save @/Router

^C
✘-INT ~/uavcan/Yukon/frontend [:4d5c7aa|✚ 2] 
23:02 $ npm install --save @/Router
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@/Router" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pavel/.npm/_logs/2019-05-08T20_02_38_572Z-debug.log
```

**Comment by Zarkopafilis** [comment]
I performed a clean install on my windows machine:

- cloned the repository and switched to correct branch (homescreen)
- `cd frontend && npm install && npm run dev`

After the dependencies were resolved and installed, the dev server for the Yukon backend ran normally.

This works on my macbook as well. Please let me know if this works.

**Comment by pavel-kirienko** [comment]
Nope, still failing. Steps to repro:

0. Get a fresh image of Mint 18 (based on Ubuntu 16.04)
1. Install nodejs v10 LTS
2. Clone https://github.com/Zarkopafilis/Yukon branch `homescreen`
3. `cd frontend && npm install && npm run dev`
4. Error posted above will appear.

**Comment by Zarkopafilis** [comment]
@pavel-kirienko You are right, I just downloaded a docker container (`node`) and it did not work. It turns out that HFS+ (the Mac filesystem) is usually configured to be case insensitive but case preserving => meaning that if you rename `frontend/src/router` to `frontend/src/Router` it is going to work. I am pushing a change later along with a very tiny python webserver for mock responses and usability testing

**Comment by Zarkopafilis** [comment]
Should be good now. If you run this with `npm run dev` and also open up `backend/devserver/mock_responses.py` (it only needs quart and quart_cors to run), you can get a functioning UI for the homescreen. GRV also has some mock data to view.

**Comment by pavel-kirienko** [comment]
Thanks! Yes, it works after I replaced `router/` with `Router/`, this change does not seem to be reflected in your PR still.

**Comment by Zarkopafilis** [comment]
As per dev-call discussion, usability testing, further integration with live updates / server event sourcing and therefore thorough testing will take place later, perhaps when the async pyuavcan is finished.

**Pull request merged**
